### ISSUE TITLE
Error while installing tokenizers package

### ISSUE THREAD

**Issue by harshakap** [ropensci/tokenizers#18] opened 2016-06-22 18:28 UTC
2016-06-22 11:37:37 (3.44 MB/s) - `/tmp/RtmpmTNniF/downloaded_packages/tokenizers_0.1.2.tar.gz' saved [41587/41587]
- installing _source_ package ‘tokenizers’ ...
  *\* package ‘tokenizers’ successfully unpacked and MD5 sums checked
  *\* libs
  I/appl/tools/R2/R-3.2.2/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/export/appl/bo6_data0_r/Packagetest/Rcpp/include"      -c RcppExports.cpp -o RcppExports.o
  /bin/sh: I/appl/tools/R2/R-3.2.2/lib64/R/include: No such file or directory
  make: [RcppExports.o] Error 127 (ignored)
  I/appl/tools/R2/R-3.2.2/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/export/appl/bo6_data0_r/Packagetest/Rcpp/include"      -c shingle_ngrams.cpp -o shingle_ngrams.o
  /bin/sh: I/appl/tools/R2/R-3.2.2/lib64/R/include: No such file or directory
  make: [shingle_ngrams.o] Error 127 (ignored)
  I/appl/tools/R2/R-3.2.2/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/export/appl/bo6_data0_r/Packagetest/Rcpp/include"      -c skip_ngrams.cpp -o skip_ngrams.o
  /bin/sh: I/appl/tools/R2/R-3.2.2/lib64/R/include: No such file or directory
  make: [skip_ngrams.o] Error 127 (ignored)
  -shared -L/appl/tools/R2/R-3.2.2/lib64/R/lib -L/usr/local/lib64 -o tokenizers.so RcppExports.o shingle_ngrams.o skip_ngrams.o -L/appl/tools/R2/R-3.2.2/lib64/R/lib -lR
  /bin/sh: line 2: -shared: command not found
  make: **\* [tokenizers.so] Error 127
  ERROR: compilation failed for package ‘tokenizers’
- removing ‘/export/appl/bo6_data0_r/Packagetest/tokenizers’

The downloaded source packages are in
        ‘/tmp/RtmpmTNniF/downloaded_packages’
Warning message:
In install.packages("tokenizers") :
  installation of package ‘tokenizers’ had non-zero exit status
///////////////////////////////////////////////////////////////////////
GCC Version:
 gcc --version
gcc (SUSE Linux) 4.3.4 [gcc-4_3-branch revision 152973]
Copyright (C) 2008 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 gcc -v
Using built-in specs.
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.3 --enable-ssp --disable-libssp --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --program-suffix=-4.3 --enable-linux-futex --without-system-libunwind --with-cpu=generic --build=x86_64-suse-linux
Thread model: posix
gcc version 4.3.4 [gcc-4_3-branch revision 152973](SUSE Linux)

**Comment by dselivanov** [comment] 2016-06-22 18:30
You need compiler with c++11 support, gcc 4.7+.
22 июня 2016 г. 9:28 PM пользователь "harshakap" notifications@github.com
написал:

**Comment by lmullen** [comment] 2016-06-22 18:52
Closing this issue since the problem is definitely the compiler. Feel free to reopen if you have further issues after updating gcc.

**Closed as completed by lmullen** 2016-06-22 18:52 UTC
