### ISSUE TITLE
R-devel / Travis

### ISSUE THREAD

**Issue by maelle** [ropensci/tokenizers#23] opened 2016-09-02 12:13 UTC
I have `tidytext` as a dependency in my `monkeylearn` package and therefore need to install `tokenizers` (one `tidytext` function I use is `unnest_token`). The Travis build fails on R-devel https://travis-ci.org/ropenscilabs/monkeylearn/jobs/157061868#L3294 "ERROR: compilation failed for package ‘tokenizers’". Do you have any idea what could cause this? Thanks!

**Comment by lmullen** [comment] 2016-09-02 12:55
The problem is a bug in Travis, I've been told. The problem has to do with the way that the Make variables are configured for compiling the package with C++11. I fixed in the commit below thanks to advice in the rOpenSci Slack. The commit makes changes to the Travis configuration. 

https://github.com/ropensci/tokenizers/commit/a5580ed7a3042f55104645324f34456a6477c39c

I'm going to close this issue, but if that doesn't solve your problem feel free to reopen.

**Closed as completed by lmullen** 2016-09-02 12:55 UTC

**Comment by maelle** [comment] 2016-09-02 13:00
Perfect, thanks a lot!
